import mongoose from 'mongoose';
import dotenv from 'dotenv';
import Product from '../models/product.model.js';

dotenv.config();

const products = [
  // Nothing Phone
  {
    brand: 'Nothing',
    series: 'Phone',
    model: '1',
    variant: '',
    year: 2022,
    rom: '256GB',
    ram: '8GB',
    cpu: 'Snapdragon 778G+',
    gpu: 'Adreno 642L',
    camera: '50MP + 12MP',
    battery: '4500mAh',
    charge: '33W',
    price: 299, // USD
    stock: Math.floor(Math.random() * 100),
    url: 'https://hu.nothing.tech/products/cmf-phone-1?Colour=Black&Capacity=8%2B128GB',
  },
  {
    brand: 'Nothing',
    series: 'Phone',
    model: '2',
    variant: '',
    year: 2023,
    rom: '256GB',
    ram: '12GB',
    cpu: 'Snapdragon 8 Gen 1',
    gpu: 'Adreno 730',
    camera: '50MP + 50MP',
    battery: '4700mAh',
    charge: '45W',
    price: 449,
    stock: Math.floor(Math.random() * 100),
    url: 'https://hu.nothing.tech/products/cmf-phone-2-pro?Colour=Orange&Capacity=8%2B128GB',
  },
  {
    brand: 'Nothing',
    series: 'Phone',
    model: '2A',
    variant: '',
    year: 2023,
    rom: '128GB',
    ram: '8GB',
    cpu: 'Snapdragon 778G',
    gpu: 'Adreno 642L',
    camera: '50MP + 12MP',
    battery: '4500mAh',
    charge: '33W',
    price: 379,
    stock: Math.floor(Math.random() * 100),
    url: 'https://nothing.tech/products/phone-2a?srsltid=AfmBOoriCQvNA0e0SL2bwUaCKZ45Z4MMdIdtDaCUr1IM1D1H_TwKphUD&Colour=Milk&Capacity=12%2B256GB',
  },
  {
    brand: 'Nothing',
    series: 'Phone',
    model: '3',
    variant: '',
    year: 2024,
    rom: '512GB',
    ram: '16GB',
    cpu: 'Snapdragon 8 Gen 2',
    gpu: 'Adreno 740',
    camera: '200MP + 12MP',
    battery: '5000mAh',
    charge: '65W',
    price: 699,
    stock: Math.floor(Math.random() * 100),
    url: 'https://www.arukereso.hu/mobiltelefon-c3277/nothing/phone-3-5g-256gb-12gb-ram-dual-p1217152603/',
  },
  {
    brand: 'Nothing',
    series: 'Phone',
    model: '3A',
    variant: '',
    year: 2024,
    rom: '256GB',
    ram: '12GB',
    cpu: 'Snapdragon 8+ Gen 1',
    gpu: 'Adreno 730',
    camera: '108MP + 12MP',
    battery: '5000mAh',
    charge: '45W',
    price: 599,
    stock: Math.floor(Math.random() * 100),
    url: 'https://nothing.tech/products/phone-3a?srsltid=AfmBOoot01OH06FEDgVxQIj8WOe9m-320NJNCt74CzIq0dR98az9XK0R&Colour=White&Capacity=8%2B128GB',
  },

  // Samsung Galaxy A
  {
    brand: 'Samsung',
    series: 'Galaxy A',
    model: '15',
    variant: '',
    year: 2023,
    rom: '128GB',
    ram: '6GB',
    cpu: 'Exynos 850',
    gpu: 'Mali-G52',
    camera: '50MP + 2MP',
    battery: '5000mAh',
    charge: '25W',
    price: 199,
    stock: Math.floor(Math.random() * 100),
    url: 'https://www.samsung.com/hu/smartphones/galaxy-a/galaxy-a15-blue-128gb-sm-a155fzbdeue/',
  },
  {
    brand: 'Samsung',
    series: 'Galaxy A',
    model: '25',
    variant: '',
    year: 2023,
    rom: '128GB',
    ram: '8GB',
    cpu: 'Exynos 1280',
    gpu: 'Mali-G68',
    camera: '64MP + 12MP',
    battery: '5000mAh',
    charge: '25W',
    price: 249,
    stock: Math.floor(Math.random() * 100),
    url: 'https://www.samsung.com/hu/smartphones/galaxy-a/galaxy-a25-5g-blue-256gb-sm-a256bzkheue/',
  },
  {
    brand: 'Samsung',
    series: 'Galaxy A',
    model: '35',
    variant: '',
    year: 2024,
    rom: '256GB',
    ram: '8GB',
    cpu: 'Exynos 1380',
    gpu: 'Mali-G68',
    camera: '50MP + 8MP + 2MP',
    battery: '5000mAh',
    charge: '33W',
    price: 299,
    stock: Math.floor(Math.random() * 100),
    url: 'https://www.samsung.com/hu/smartphones/galaxy-a/galaxy-a35-5g-awesome-iceblue-128gb-sm-a356blbbeue/',
  },
  {
    brand: 'Samsung',
    series: 'Galaxy A',
    model: '55',
    variant: '',
    year: 2024,
    rom: '256GB',
    ram: '12GB',
    cpu: 'Snapdragon 8 Gen 2',
    gpu: 'Adreno 740',
    camera: '200MP + 12MP + 12MP',
    battery: '5000mAh',
    charge: '45W',
    price: 449,
    stock: Math.floor(Math.random() * 100),
    url: 'https://www.samsung.com/hu/smartphones/galaxy-a/galaxy-a55-5g-awesome-iceblue-128gb-sm-a556blbaeue/',
  },

  // Samsung Galaxy S
  {
    brand: 'Samsung',
    series: 'Galaxy S',
    model: '24',
    variant: '',
    year: 2024,
    rom: '128GB',
    ram: '8GB',
    cpu: 'Snapdragon 8 Gen 2',
    gpu: 'Adreno 740',
    camera: '50MP + 12MP + 10MP',
    battery: '4500mAh',
    charge: '45W',
    price: 899,
    stock: Math.floor(Math.random() * 100),
    url: 'https://www.samsung.com/hu/smartphones/galaxy-s24/buy/',
  },
  {
    brand: 'Samsung',
    series: 'Galaxy S',
    model: '24',
    variant: 'FE',
    year: 2024,
    rom: '256GB',
    ram: '8GB',
    cpu: 'Snapdragon 8 Gen 3',
    gpu: 'Adreno 750',
    camera: '108MP + 12MP',
    battery: '4500mAh',
    charge: '25W',
    price: 649,
    stock: Math.floor(Math.random() * 100),
    url: 'https://www.samsung.com/hu/smartphones/galaxy-s/galaxy-s24-fe-blue-128gb-sm-s721blbdeue/',
  },
  {
    brand: 'Samsung',
    series: 'Galaxy S',
    model: '24',
    variant: 'Ultra',
    year: 2024,
    rom: '512GB',
    ram: '16GB',
    cpu: 'Snapdragon 8 Gen 3',
    gpu: 'Adreno 750',
    camera: '200MP + 12MP + 12MP',
    battery: '5000mAh',
    charge: '45W',
    price: 1199,
    stock: Math.floor(Math.random() * 100),
    url: 'https://www.samsung.com/hu/smartphones/galaxy-s24-ultra/',
  },
  {
    brand: 'Samsung',
    series: 'Galaxy S',
    model: '25',
    variant: '',
    year: 2025,
    rom: '256GB',
    ram: '12GB',
    cpu: 'Snapdragon 8 Gen 3',
    gpu: 'Adreno 750',
    camera: '108MP + 12MP + 12MP',
    battery: '4700mAh',
    charge: '65W',
    price: 1099,
    stock: Math.floor(Math.random() * 100),
    url: 'https://www.fizz.hu/p/mobiltelefonok/samsung-galaxy-s25-okostelefon-12gb-128gb-jeges-kek/LY2ETXGQE?utm_source=google&utm_medium=cpc&utm_campaign=pmax_always-on_trending&utm_id=&gclsrc=aw.ds&gad_source=1&gad_campaignid=23301840201&gbraid=0AAAAApHpwwsZ5lch4sniIDKp6kXL9d0bM&gclid=Cj0KCQiA5I_NBhDVARIsAOrqIsZzvJ6E_uOkEdmk5qK73uk4Tm_CL67bZlH_2HH_U0NtWJ9O8HfRb38aAuwjEALw_wcB',
  },
  {
    brand: 'Samsung',
    series: 'Galaxy S',
    model: '25',
    variant: 'FE',
    year: 2025,
    rom: '128GB',
    ram: '8GB',
    cpu: 'Snapdragon 8 Gen 3',
    gpu: 'Adreno 750',
    camera: '50MP + 12MP',
    battery: '4500mAh',
    charge: '45W',
    price: 749,
    stock: Math.floor(Math.random() * 100),
    url: 'https://www.notebook.hu/sorozatok?sorozat=Galaxy+S25+FE&utm_campaign=SERIES-Samsung-CPC&gad_source=1&gad_campaignid=21913629993&gbraid=0AAAAADtH21LUI3gUSVmrI2O7Gt9lxBBpF&gclid=Cj0KCQiA5I_NBhDVARIsAOrqIsZHab0M2AfYUDKzkVrT0mugArgxaZWqQ0xs9moOtfKJYGpyPY0CLbcaAk3nEALw_wcB',
  },
  {
    brand: 'Samsung',
    series: 'Galaxy S',
    model: '25',
    variant: 'Ultra',
    year: 2025,
    rom: '512GB',
    ram: '16GB',
    cpu: 'Snapdragon 8 Gen 3',
    gpu: 'Adreno 750',
    camera: '200MP + 12MP + 12MP + 12MP',
    battery: '5000mAh',
    charge: '65W',
    price: 1299,
    stock: Math.floor(Math.random() * 100),
    url: 'https://www.samsung.com/hu/smartphones/galaxy-s25-ultra/',
  },
  // Xiaomi 15
  {
    brand: 'Xiaomi',
    series: '15',
    model: 'N/A',
    variant: '',
    year: 2024,
    rom: '512GB',
    ram: '12GB',
    cpu: 'Snapdragon 8 Gen 3',
    gpu: 'Adreno 750',
    camera: '200MP + 12MP + 12MP',
    battery: '5100mAh',
    charge: '120W',
    price: 899,
    stock: Math.floor(Math.random() * 100),
    url: 'https://www.mi.com/hu/product/xiaomi-15/',
  },
  {
    brand: 'Xiaomi',
    series: '15',
    model: 'ultra',
    variant: '',
    year: 2025,
    rom: '256GB',
    ram: '12GB',
    cpu: 'Snapdragon 8 Gen 3',
    gpu: 'Adreno 740',
    camera: '200MP + 50MP + 12MP',
    battery: '4800mAh',
    charge: '120W',
    price: 999,
    stock: Math.floor(Math.random() * 100),
    url: 'https://www.mi.com/hu/product/xiaomi-15-ultra/',
  },
  {
    brand: 'Xiaomi',
    series: '17',
    model: 'N/A',
    variant: '',
    year: 2025,
    rom: '512GB',
    ram: '16GB',
    cpu: 'Snapdragon 8 Gen 3',
    gpu: 'Adreno 740',
    camera: '200MP + 50MP + 12MP',
    battery: '5000mAh',
    charge: '120W',
    price: 1199,
    stock: Math.floor(Math.random() * 100),
    url: 'https://www.alza.hu/xiaomi-17-12gb-512gb-fekete-d13254765.htm?kampan=adw1_alza_pmax_all_akv-rh-top_obecna_c_9107132____~~&gad_source=1&gad_campaignid=23027181032&gbraid=0AAAAAD2xsm5z6PKAaKTV8TGuY-2WSgQV1&gclid=Cj0KCQiA5I_NBhDVARIsAOrqIsbr26EFaKYTjH9mVc74L5T2rz9qBSn0vl2gGMuUrFun5V9ft7_2KNMaAr-YEALw_wcB',
  },
];

const seedDB = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI!);
    console.log('MongoDB connected for seeding');

    await Product.deleteMany({});
    console.log('Existing products removed');

    await Product.insertMany(products);
    console.log('Products inserted');

    process.exit(0);
  } catch (error) {
    console.error(error);
    process.exit(1);
  }
};

seedDB();
